// Generated by dia2code
#ifndef STATE__BUILDINGTYPE__H
#define STATE__BUILDINGTYPE__H


namespace state {

  enum BuildingType {
    BASE     = 0,
    CITY     = 1,
    FACTORY     = 2,
    AIRPORT     = 3,
    SEAPORT     = 4
  };

};

#endif
