// Generated by dia2code
#ifndef STATE__BUILDING__H
#define STATE__BUILDING__H


#include "BuildingTeam.h"
#include "BuildingType.h"

namespace state {

  /// class Building - 
  class Building {
    // Associations
    // Attributes
  protected:
    int x;
    int y;
    int capturePoints     = 20;
    BuildingTeam buildingTeam;
    BuildingType buildingType;
    // Operations
  public:
    BuildingType getBuildingType ();
    BuildingTeam getTeam ();
    bool isInCapture ();
    // Setters and Getters
    int getX() const;
    void setX(int x);
    int getY() const;
    void setY(int y);
    int getCapturePoints() const;
    void setCapturePoints(int capturePoints);
    BuildingTeam getBuildingTeam() const;
    void setBuildingTeam(BuildingTeam buildingTeam);
    void setBuildingType(BuildingType buildingType);
  };

};

#endif
