// Generated by dia2code
#ifndef STATE__BUILDING__H
#define STATE__BUILDING__H

#include <stdlib.h>

namespace state {
  class Cell;
}

#include "Team.h"
#include "CellType.h"
#include "Cell.h"

namespace state {

  /// class Building - 
  class Building : public state::Cell {
    // Attributes
  protected:
    int capturePoints;
    // Operations
  public:
    Building (Team team = NEUTRAL, CellType type = CT_CITY, size_t x = 0, size_t y = 0);
    bool isInCapture () const;
    void debug () const;
    // Setters and Getters
    int getCapturePoints() const;
    void setCapturePoints(int capturePoints);
  };

};

#endif
