// Generated by dia2code
#ifndef STATE__BUILDINGTEAM__H
#define STATE__BUILDINGTEAM__H


namespace state {

  enum BuildingTeam {
    Neutral     = 0,
    Player1     = 1,
    Player2     = 2
  };

};

#endif
