// Generated by dia2code
#ifndef STATE__BUILDINGTEAM__H
#define STATE__BUILDINGTEAM__H


namespace state {

  enum BuildingTeam {
    BT_NEUTRAL     = 0,
    BT_PLAYER1     = 1,
    BT_PLAYER2     = 2
  };

};

#endif
