// Generated by dia2code
#ifndef STATE__BUILDINGTYPE__H
#define STATE__BUILDINGTYPE__H


namespace state {

  enum BuildingType {
    BT_BASE     = 0,
    BT_CITY     = 1,
    BT_FACTORY     = 2,
    BT_AIRPORT     = 3,
    BT_SEAPORT     = 4
  };

};

#endif
