// Generated by dia2code
#ifndef STATE__CELL__H
#define STATE__CELL__H


namespace state {
  class Element;
}

#include "CellType.h"
#include "Element.h"

namespace state {

  /// class Cell - 
  class Cell : public state::Element {
    // Associations
    // Attributes
  protected:
    CellType cellType;
    // Operations
  public:
    Cell (CellType cellType = CT_PLAIN, int x = 0, int y = 0);
    void debug () const;
    // Setters and Getters
    CellType getCellType() const;
    void setCellType(CellType cellType);
  };

};

#endif
