// Generated by dia2code
#ifndef STATE__CELLTYPE__H
#define STATE__CELLTYPE__H


namespace state {

  enum CellType {
    CT_GROUND     = 0,
    CT_ROAD     = 1,
    CT_FOREST     = 2,
    CT_MOUNTAIN     = 3,
    CT_RIVER     = 4,
    CT_BRIDGE     = 5,
    CT_SEA     = 6,
    CT_BUILDING     = 7,
    CT_BASE     = 8
  };

};

#endif
