// Generated by dia2code
#ifndef STATE__CELL__H
#define STATE__CELL__H

#include <memory>

namespace state {
  class Building;
  class Unit;
}

#include "Building.h"
#include "Unit.h"
#include "CellType.h"

namespace state {

  /// class Cell - 
  class Cell {
    // Associations
    // Attributes
  protected:
    int x;
    int y;
    std::unique_ptr<Building> building;
    std::unique_ptr<Unit> unit;
    CellType cellType;
    // Operations
  public:
    Building* getBuilding ();
    Unit* getUnit ();
    CellType getCellType ();
    // Setters and Getters
    int getX() const;
    void setX(int x);
    int getY() const;
    void setY(int y);
    void setBuilding(const std::unique_ptr<Building>& building);
    void setUnit(const std::unique_ptr<Unit>& unit);
    void setCellType(CellType cellType);
  };

};

#endif
