// Generated by dia2code
#ifndef STATE__CELLTYPE__H
#define STATE__CELLTYPE__H


namespace state {

  enum CellType {
    CT_NONE     = -1,
    CT_PLAIN     = 0,
    CT_ROAD     = 1,
    CT_FOREST     = 2,
    CT_MOUNTAIN     = 3,
    CT_RIVER     = 4,
    CT_BRIDGE     = 5,
    CT_SEA     = 6,
    CT_BASE     = 7,
    CT_CITY     = 8,
    CT_FACTORY     = 9,
    CT_AIRPORT     = 10,
    CT_SEAPORT     = 11
  };

};

#endif
