// Generated by dia2code
#ifndef STATE__ELEMENT__H
#define STATE__ELEMENT__H


#include "TypeId.h"
#include "Team.h"

namespace state {

  /// class Element - 
  class Element {
    // Associations
    // Attributes
  protected:
    TypeId type;
    Team team     = NEUTRAL;
    int x     = 0;
    int y     = 0;
    // Operations
  public:
    Element (TypeId type, Team team = NEUTRAL, int x = 0, int y = 0);
    bool const isUnit ();
    // Setters and Getters
    TypeId getType() const;
    void setType(TypeId type);
    Team getTeam() const;
    void setTeam(Team team);
    int getX() const;
    void setX(int x);
    int getY() const;
    void setY(int y);
  };

};

#endif
