// Generated by dia2code
#ifndef STATE__ELEMENTTAB__H
#define STATE__ELEMENTTAB__H

#include <vector>

namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  /// class ElementTab - 
  class ElementTab {
    // Associations
    // Attributes
  protected:
    int width;
    int height;
    std::vector<Element*> elemList;
    std::vector<Element*> elemTab;
    // Operations
  public:
    ElementTab (int w, int h);
    void addElem (Element* elem);
    Element* getElem (int i);
    const Element* operator[] (int i) const;
    Element* operator[] (int i);
    const Element* getElem (int x, int y) const;
    Element* getElem (int x, int y);
    void eraseElem (int i);
    void eraseElem (int x, int y);
    // Setters and Getters
    int getWidth() const;
    void setWidth(int width);
    int getHeight() const;
    void setHeight(int height);
    const std::vector<Element*>& getElemList() const;
    void setElemList(const std::vector<Element*>& elemList);
    const std::vector<Element*>& getElemTab() const;
    void setElemTab(const std::vector<Element*>& elemTab);
  };

};

#endif
