// Generated by dia2code
#ifndef STATE__PLAYER__H
#define STATE__PLAYER__H


namespace state {
  class Building;
  class Unit;
}

#include "Building.h"
#include "Unit.h"

namespace state {

  /// class Player - 
  class Player {
    // Associations
    // Attributes
  protected:
    int PlayerID;
    vector<unique_ptr<Unit>> unitList;
    vector<unique_ptr<Building>> buildingList;
    // Operations
  public:
    Building* getBuilding (int i);
    Unit* getUnit (int i);
    // Setters and Getters
    int getPlayerID() const;
    void setPlayerID(int PlayerID);
    const vector<unique_ptr<Unit>>& getUnitList() const;
    void setUnitList(const vector<unique_ptr<Unit>>& unitList);
    const vector<unique_ptr<Building>>& getBuildingList() const;
    void setBuildingList(const vector<unique_ptr<Building>>& buildingList);
  };

};

#endif
