// Generated by dia2code
#ifndef STATE__STATE__H
#define STATE__STATE__H

#include <vector>
#include <string>

namespace state {
  class ElementTab;
  class Player;
}

#include "ElementTab.h"
#include "Player.h"

namespace state {

  /// class State - 
  class State {
    // Associations
    // Attributes
  protected:
    int w;
    int h;
    ElementTab cellTab;
    std::vector<Player> players;
    // Operations
  public:
    State (std::string levelFile);
    State ();
    ElementTab& getUnitTab () const;
    // Setters and Getters
    int getW() const;
    void setW(int w);
    int getH() const;
    void setH(int h);
    const ElementTab& getCellTab() const;
    void setCellTab(const ElementTab& cellTab);
    const std::vector<Player>& getPlayers() const;
    void setPlayers(const std::vector<Player>& players);
  };

};

#endif
