// Generated by dia2code
#ifndef STATE__TEAM__H
#define STATE__TEAM__H


namespace state {

  enum Team {
    NONE    	= -1,
    NEUTRAL     = 0,
    PLAYER1     = 1,
    PLAYER2     = 2
  };

};

#endif
