// Generated by dia2code
#ifndef STATE__TYPEID__H
#define STATE__TYPEID__H


namespace state {

  enum TypeId {
    T_NONE     = -1,
    T_UNIT     = 0,
    T_CELL     = 1,
    T_BUILDING     = 2
  };

};

#endif
