// Generated by dia2code
#ifndef STATE__UNITTYPE__H
#define STATE__UNITTYPE__H


namespace state {

  enum UnitType {
    UT_NONE     = -1,
    UT_INFANTRY     = 0,
    UT_MECH     = 1,
    UT_RECON     = 2,
    UT_TANK     = 3,
    UT_TANKM     = 4,
    UT_APC     = 5,
    UT_AATANK     = 6,
    UT_AAMISSILELAUNCHER     = 7,
    UT_ARTILLERY     = 8,
    UT_MISSILELAUNCHER     = 9,
    UT_FIGHTER     = 10,
    UT_BOMBER     = 11,
    UT_BATTELHELI     = 12,
    UT_TRANSPORTHELI     = 13,
    UT_BATTLESHIP     = 14,
    UT_CRUISER     = 15,
    UT_LANDER     = 16,
    UT_SUBMARINE     = 17
  };

};

#endif
