// Generated by dia2code
#ifndef STATE__UNIT__H
#define STATE__UNIT__H


#include "UnitTeam.h"
#include "UnitType.h"

namespace state {

  /// class Unit - 
  class Unit {
    // Associations
    // Attributes
  protected:
    int x;
    int y;
    int health;
    int ammo;
    int fuel;
    int vision;
    UnitTeam unitTeam;
    UnitType unitType;
    // Operations
  public:
    Unit ( );
    Unit (int x, int y, UnitType uType, UnitTeam team);
    bool isInfantry ();
    bool isCapturing ();
    bool isRanged ();
    bool isTransporter ();
    // Setters and Getters
    int getX() const;
    void setX(int x);
    int getY() const;
    void setY(int y);
    int getHealth() const;
    void setHealth(int health);
    int getAmmo() const;
    void setAmmo(int ammo);
    int getFuel() const;
    void setFuel(int fuel);
    int getVision() const;
    void setVision(int vision);
    UnitTeam getUnitTeam() const;
    void setUnitTeam(UnitTeam unitTeam);
    UnitType getUnitType() const;
    void setUnitType(UnitType unitType);
  };

};

#endif
