// Generated by dia2code
#ifndef STATE__UNITTYPE__H
#define STATE__UNITTYPE__H


namespace state {

  enum UnitType {
    INFANTRY     = 0,
    MECH     = 1,
    RECON     = 2,
    TANK     = 3,
    TANKM     = 4,
    APC     = 5,
    AATANK     = 6,
    AAMISSILELAUNCHER     = 7,
    ARTILLERY     = 8,
    MISSILELAUNCHER     = 9,
    FIGHTER     = 10,
    BOMBER     = 11,
    BATTELHELI     = 12,
    TRANSPORTHELI     = 13,
    BATTLESHIP     = 14,
    CRUISER     = 15,
    LANDER     = 16,
    SUBMARINE     = 17
  };

};

#endif
