// Generated by dia2code
#ifndef STATE__UNIT__H
#define STATE__UNIT__H

#include <stdlib.h>

namespace state {
  class Element;
}

#include "UnitType.h"
#include "Team.h"
#include "Element.h"

namespace state {

  /// class Unit - 
  class Unit : public state::Element {
    // Associations
    // Attributes
  protected:
    UnitType unitType;
    int health;
    int ammo;
    int fuel;
    int vision;
    bool available     = false;
    bool moved     = true;
    // Operations
  public:
    Unit (Team team = PLAYER1, UnitType utype = UT_INFANTRY, size_t x = 0, size_t y = 0);
    bool isInfantry () const;
    bool isRanged () const;
    bool isTransporter () const;
    bool isCapturing () const;
    void debug () const;
    // Setters and Getters
    UnitType getUnitType() const;
    void setUnitType(UnitType unitType);
    int getHealth() const;
    void setHealth(int health);
    int getAmmo() const;
    void setAmmo(int ammo);
    int getFuel() const;
    void setFuel(int fuel);
    int getVision() const;
    void setVision(int vision);
    bool getAvailable() const;
    void setAvailable(bool available);
    bool getMoved() const;
    void setMoved(bool moved);
  };

};

#endif
