// Generated by dia2code
#ifndef RENDER__BOARDLAYER__H
#define RENDER__BOARDLAYER__H

#include <vector>

namespace state {
  class Element;
};
namespace render {
  class Layer;
}

#include "Layer.h"

namespace render {

  /// class BoardLayer - 
  class BoardLayer : public render::Layer {
    // Operations
  public:
    void update (const std::vector<state::Element*> tab);
    // Setters and Getters
  };

};

#endif
