// Generated by dia2code
#ifndef RENDER__BOARDLAYER__H
#define RENDER__BOARDLAYER__H


namespace render {
  class Layer;
}

#include "Layer.h"

namespace render {

  /// class BoardLayer - 
  class BoardLayer : public render::Layer {
    // Setters and Getters
  };

};

#endif
