// Generated by dia2code
#ifndef RENDER__BOARDLAYER__H
#define RENDER__BOARDLAYER__H

#include <vector>
#include <memory>

namespace state {
  class Element;
};
namespace render {
  class Layer;
}

#include "state/Element.h"
#include "Layer.h"

namespace render {

  /// class BoardLayer - 
  class BoardLayer : public render::Layer {
    // Operations
  public:
    void update (const std::vector<std::shared_ptr<state::Element>> tab);
    // Setters and Getters
  };

};

#endif
