// Generated by dia2code
#ifndef RENDER__BUILDINGTILESET__H
#define RENDER__BUILDINGTILESET__H

#include <string>

namespace state {
  class Building;
};
namespace render {
  class TileSet;
}

#include "state/Building.h"
#include "TileSet.h"

namespace render {

  /// class BuildingTileSet - 
  class BuildingTileSet : public render::TileSet {
    // Attributes
  public:
    std::vector<Building> buildings;
    int const buildingWidth;
    int const buildingHeight;
    std::string const imageFile;
    // Operations
  public:
    BuildingTIleSet ();
    int const getBuildingWidth ();
    void setBuildingWidth(int const buildingWidth);
    int const getBuildingHeight ();
    void setBuildingHeight(int const buildingHeight);
    const std::string const getImageFile ();
    void setImageFile(std::string imageFile);
    // Setters and Getters
  };

};

#endif
