// Generated by dia2code
#ifndef RENDER__BUILDINGTILESET__H
#define RENDER__BUILDINGTILESET__H

#include <vector>
#include <string>

namespace state {
  class Building;
};
namespace render {
  class TileSet;
}

#include "state/Building.h"
#include "TileSet.h"

namespace render {

  /// class BuildingTileSet - 
  class BuildingTileSet : public render::TileSet {
    // Attributes
  protected:
    std::vector<state::Building> buildings;
    // Operations
  public:
    BuildingTileSet ();
    std::string getImageFile () const;
    state::Building& getBuildingTile (char b) const;
    // Setters and Getters
    const std::vector<state::Building>& getBuildings() const;
    void setBuildings(const std::vector<state::Building>& buildings);
  };

};

#endif
