// Generated by dia2code
#ifndef RENDER__CELLTILESET__H
#define RENDER__CELLTILESET__H

#include <vector>
#include <string>

namespace state {
  class Cell;
};
namespace render {
  class TileSet;
}

#include "state/Cell.h"
#include "TileSet.h"

namespace render {

  /// class CellTileSet - 
  class CellTileSet : public render::TileSet {
    // Attributes
  public:
    std::vector<Cell> cells;
    int const cellWidth;
    int const cellHeight;
    const std::string const imageFile;
    // Operations
  public:
    CellTileSet ();
    int const getCellWidth ();
    void setCellWidth(int cellWidth);
    int const getCellHeight ();
    void setCellHeight(int cellHeight);
    const std::string const getImageFile ();
    void setImageFIle(std::string imageFile);
    //const Cell& const getCellTile (char c);
    // Setters and Getters
  };

};

#endif
