// Generated by dia2code
#ifndef RENDER__CELLTILESET__H
#define RENDER__CELLTILESET__H

#include <vector>
#include <string>

namespace state {
  class Cell;
};
namespace render {
  class TileSet;
}

#include "state/Cell.h"
#include "TileSet.h"

namespace render {

  /// class CellTileSet - 
  class CellTileSet : public render::TileSet {
    // Attributes
  public:
    std::vector<state::Cell> cells;
    // Operations
  public:
    CellTileSet ();
    std::string getImageFile () const;
    state::Cell& getCellTile (char c) const;
    // Setters and Getters
  };

};

#endif
