// Generated by dia2code
#ifndef RENDER__ELEMENTTABLAYER__H
#define RENDER__ELEMENTTABLAYER__H

#include <vector>

namespace state {
  class Building;
  class Unit;
  class Cell;
};
namespace render {
  class Layer;
};
namespace state {
  class State;
}

#include "Layer.h"
#include "state/State.h"

namespace render {

  /// class ElementTabLayer - 
  class ElementTabLayer : public render::Layer {
    // Associations
    // Attributes
  private:
    const state::std::vector<Building*> buildingList;
    const state::std::vector<Unit*> unitList;
    const Cell* board;
    // Operations
  public:
    UnitLayer (const state::std::vector<Unit*> unitList);
    buildingLayer (const state::std::vector<Building*> buildingList);
    boardLayer (const Cell* board);
    void initSurface ();
    // Setters and Getters
  };

};

#endif
