// Generated by dia2code
#ifndef RENDER__INTERFACELAYER__H
#define RENDER__INTERFACELAYER__H


namespace state {
  class State;
};
namespace render {
  class Layer;
}

#include "Layer.h"
#include "state/State.h"

namespace render {

  /// class InterfaceLayer - 
  class InterfaceLayer : public render::Layer {
    // Associations
    // Attributes
  protected:
    int buildingCount[3];
    int unitCount[2];
    // Operations
  public:
    InterfaceLayer (const state::State& state);
    void initSurface ();
    // Setters and Getters
    int getBuildingCount[3]() const;
    void setBuildingCount[3](int buildingCount[3]);
    int getUnitCount[2]() const;
    void setUnitCount[2](int unitCount[2]);
  };

};

#endif
