// Generated by dia2code
#ifndef RENDER__LAYER__H
#define RENDER__LAYER__H

#include <string>
#include <SFML/Graphics.hpp>

namespace render {
  class Surface;
  class TileSet;
};
namespace sf {
  class RenderWindow;
}

#include "Surface.h"
#include "TileSet.h"

namespace render {

  /// class Layer - 
  class Layer {
    // Associations
    // Attributes
  protected:
    Surface* surface;
    TileSet* tileSet;
    // Operations
  public:
    const Surface* getSurface () const;
    void print (int x, int y, std::string text);
    void draw (sf::RenderWindow& window);
    // Setters and Getters
    void setSurface(const Surface*& surface);
    const TileSet*& getTileSet() const;
    void setTileSet(const TileSet*& tileSet);
  };

};

#endif
