// Generated by dia2code
#ifndef RENDER__LAYER__H
#define RENDER__LAYER__H

#include <memory>
#include <string>

namespace render {
  class Surface;
  class TileSet;
}

#include "Surface.h"
#include "TileSet.h"

namespace render {

  /// class Layer - 
  class Layer {
    // Associations
    // Attributes
  protected:
    std::unique_ptr<Surface> surfaceTab;
    std::shared_ptr<TileSet> tilesetTab;
    const Surface* const surface;
    // Operations
  public:
    Layer ();
    virtual ~Layer ();
    const Surface* const getSurface ();
    void setSurface(Surface* surface);
    void initSurface ();
    void printText(int x, int y, const std::string& msg);
    // Setters and Getters
    const std::shared_ptr<TileSet>& getTileset() const;
    void setTileset(const std::shared_ptr<TileSet>& tileset);
  };

};

#endif
