// Generated by dia2code
#ifndef RENDER__RENDER__H
#define RENDER__RENDER__H


namespace render {
  class StatusLayer;
  class BoardLayer;
}

#include "StatusLayer.h"
#include "BoardLayer.h"

namespace render {

  /// class Render - 
  class Render {
    // Associations
    // Attributes
  protected:
    StatusLayer statusLayer;
    BoardLayer cellLayer;
    BoardLayer buildingLayer;
    BoardLayer unitLayer;
    // Operations
  public:
    void draw ();
    // Setters and Getters
    const StatusLayer& getStatusLayer() const;
    void setStatusLayer(const StatusLayer& statusLayer);
    const BoardLayer& getCellLayer() const;
    void setCellLayer(const BoardLayer& cellLayer);
    const BoardLayer& getBuildingLayer() const;
    void setBuildingLayer(const BoardLayer& buildingLayer);
    const BoardLayer& getUnitLayer() const;
    void setUnitLayer(const BoardLayer& unitLayer);
  };

};

#endif
