// Generated by dia2code
#ifndef RENDER__STATUSLAYER__H
#define RENDER__STATUSLAYER__H


namespace render {
  class Layer;
}

#include "Layer.h"

namespace render {

  /// class StatusLayer - 
  class StatusLayer : public render::Layer {
    // Setters and Getters
  };

};

#endif
