// Generated by dia2code
#ifndef RENDER__SURFACE__H
#define RENDER__SURFACE__H

#include <SFML/Graphics.hpp>
#include <string>

namespace sf {
  class VertexArray;
  class Texture;
};
namespace render {
  class Tile;
};
namespace sf {
  class Transformable;
  class Drawable;
};
namespace render {
  class TileSet;
}

#include "TileSet.h"

namespace render {

  /// class Surface - 
  class Surface : public sf::Transformable, public sf::Drawable {
    // Attributes
  protected:
    sf::VertexArray vertices;
    sf::Texture texture;
    // Operations
  public:
    void loadTexture (const std::string& fileName);
    void initVertices (int n);
    void setSpriteLocation (int i, int x, int y);
    void setSpriteTexture (int i, const Tile& tile);
    void draw (sf::RenderTarget& target, sf::RenderStates states) const;
    // Setters and Getters
    const sf::VertexArray& getVertices() const;
    void setVertices(const sf::VertexArray& vertices);
    const sf::Texture& getTexture() const;
    void setTexture(const sf::Texture& texture);
  };

};

#endif
