// Generated by dia2code
#ifndef RENDER__SURFACE__H
#define RENDER__SURFACE__H

#include <SFML/Graphics.hpp>
#include <string>

namespace state {
  class Unit;
  class Building;
}

namespace render {

  /// class Surface - 
  class Surface {
    // Attributes
  public:
    sf::Texture texture;
    sf::VertexArray quads;
    // Operations
  public:
    void loadTexture (const std::string& image_file);
    void initQuads (int count);
    void setUnitLocation (int i, int x, int y);
    void setUnitTexture (int i, const Unit& unit);
    void setBuildingLocation (int i, int x, int y);
    void setBuildingTexture (int i, const Building& building);
    void const draw (sf::RenderTarget& target, sf:RenderState states);
    // Setters and Getters
  };

};

#endif
