// Generated by dia2code
#ifndef RENDER__TILESET__H
#define RENDER__TILESET__H

#include <string>

namespace render {
  class Tile;
};
namespace state {
  class Element;
}

#include "Tile.h"
#include "state/Element.h"

namespace render {

  /// class TileSet - 
  class TileSet {
    // Operations
  public:
    virtual int getCellWidth () const;
    virtual int getCellHeight () const;
    virtual std::string getFile () const;
    virtual const Tile getTile (int id) const;
    // Setters and Getters
  };

};

#endif
