// Generated by dia2code
#ifndef RENDER__TILE__H
#define RENDER__TILE__H


namespace render {

  /// class Tile - 
  class Tile {
    // Attributes
  public:
    int x     = 0;
    int y     = 0;
    int w     = 16;
    int h     = 16;
    // Operations
  public:
    Tile ();
    Tile (int x, int y, int w = 16, int h = 16);
    // Setters and Getters
  };

};

#endif
