// Generated by dia2code
#ifndef RENDER__UNITTILESET__H
#define RENDER__UNITTILESET__H

#include <vector>
#include <string>

namespace state {
  class Unit;
};
namespace render {
  class TileSet;
}

#include "state/Unit.h"
#include "TileSet.h"

namespace render {

  /// class UnitTileSet - 
  class UnitTileSet : public render::TileSet {
    // Attributes
  public:
    std::vector<state::Unit> units;
    // Operations
  public:
    UnitTileSet ();
    std::string getImageFile () const;
    state::Unit& getUnitTile (char u) const;
    // Setters and Getters
  };

};

#endif
