// Generated by dia2code
#ifndef RENDER__UNITTILESET__H
#define RENDER__UNITTILESET__H

#include <vector>
#include <string>

namespace state {
  class Unit;
};
namespace render {
  class TileSet;
}

#include "state/Unit.h"
#include "TileSet.h"

namespace render {

  /// class UnitTileSet - 
  class UnitTileSet : public render::TileSet {
    // Attributes
  public:
    std::vector<Unit> units;
    int const unitWidth;
    int const unitHeight;
    const std::string const imageFile;
    // Operations
  public:
    UnitTileSet ();
    int const getUnitWidth ();
    void setUnitWidth(int const unitWidth);
    int const getUnitHeight();
    void getUnitHeight(int const unitHeight);
    const std::string const getImageFile ();
    void settImageFile(std::string const imageFile);
    const Unit& const getUnitTile (char u);
    // Setters and Getters
  };

};

#endif
