# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ren/Desktop/IS/renwongwanit

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ren/Desktop/IS/renwongwanit

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ren/Desktop/IS/renwongwanit/CMakeFiles /home/ren/Desktop/IS/renwongwanit/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ren/Desktop/IS/renwongwanit/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

src/client/Building.o: src/client/Building.cpp.o

.PHONY : src/client/Building.o

# target to build an object file
src/client/Building.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Building.cpp.o
.PHONY : src/client/Building.cpp.o

src/client/Building.i: src/client/Building.cpp.i

.PHONY : src/client/Building.i

# target to preprocess a source file
src/client/Building.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Building.cpp.i
.PHONY : src/client/Building.cpp.i

src/client/Building.s: src/client/Building.cpp.s

.PHONY : src/client/Building.s

# target to generate assembly for a file
src/client/Building.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Building.cpp.s
.PHONY : src/client/Building.cpp.s

src/client/Cell.o: src/client/Cell.cpp.o

.PHONY : src/client/Cell.o

# target to build an object file
src/client/Cell.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Cell.cpp.o
.PHONY : src/client/Cell.cpp.o

src/client/Cell.i: src/client/Cell.cpp.i

.PHONY : src/client/Cell.i

# target to preprocess a source file
src/client/Cell.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Cell.cpp.i
.PHONY : src/client/Cell.cpp.i

src/client/Cell.s: src/client/Cell.cpp.s

.PHONY : src/client/Cell.s

# target to generate assembly for a file
src/client/Cell.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Cell.cpp.s
.PHONY : src/client/Cell.cpp.s

src/client/Player.o: src/client/Player.cpp.o

.PHONY : src/client/Player.o

# target to build an object file
src/client/Player.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Player.cpp.o
.PHONY : src/client/Player.cpp.o

src/client/Player.i: src/client/Player.cpp.i

.PHONY : src/client/Player.i

# target to preprocess a source file
src/client/Player.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Player.cpp.i
.PHONY : src/client/Player.cpp.i

src/client/Player.s: src/client/Player.cpp.s

.PHONY : src/client/Player.s

# target to generate assembly for a file
src/client/Player.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Player.cpp.s
.PHONY : src/client/Player.cpp.s

src/client/Unit.o: src/client/Unit.cpp.o

.PHONY : src/client/Unit.o

# target to build an object file
src/client/Unit.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Unit.cpp.o
.PHONY : src/client/Unit.cpp.o

src/client/Unit.i: src/client/Unit.cpp.i

.PHONY : src/client/Unit.i

# target to preprocess a source file
src/client/Unit.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Unit.cpp.i
.PHONY : src/client/Unit.cpp.i

src/client/Unit.s: src/client/Unit.cpp.s

.PHONY : src/client/Unit.s

# target to generate assembly for a file
src/client/Unit.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Unit.cpp.s
.PHONY : src/client/Unit.cpp.s

src/client/main.o: src/client/main.cpp.o

.PHONY : src/client/main.o

# target to build an object file
src/client/main.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/main.cpp.o
.PHONY : src/client/main.cpp.o

src/client/main.i: src/client/main.cpp.i

.PHONY : src/client/main.i

# target to preprocess a source file
src/client/main.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/main.cpp.i
.PHONY : src/client/main.cpp.i

src/client/main.s: src/client/main.cpp.s

.PHONY : src/client/main.s

# target to generate assembly for a file
src/client/main.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/main.cpp.s
.PHONY : src/client/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... client"
	@echo "... src/client/Building.o"
	@echo "... src/client/Building.i"
	@echo "... src/client/Building.s"
	@echo "... src/client/Cell.o"
	@echo "... src/client/Cell.i"
	@echo "... src/client/Cell.s"
	@echo "... src/client/Player.o"
	@echo "... src/client/Player.i"
	@echo "... src/client/Player.s"
	@echo "... src/client/Unit.o"
	@echo "... src/client/Unit.i"
	@echo "... src/client/Unit.s"
	@echo "... src/client/main.o"
	@echo "... src/client/main.i"
	@echo "... src/client/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

