// Generated by dia2code
#ifndef RENDER__BOARDLAYER__H
#define RENDER__BOARDLAYER__H


namespace render {
  class Surface;
  class TileSet;
};
namespace state {
  class ElementTab;
};
namespace render {
  class Layer;
}

#include "Layer.h"
#include "state/ElementTab.h"

namespace render {

  /// class BoardLayer - 
  class BoardLayer : public render::Layer {
    // Operations
  public:
    BoardLayer (Surface* surface, TileSet* tileset);
    void update (const state::ElementTab& tab);
    // Setters and Getters
  };

};

#endif
