// Generated by dia2code
#ifndef RENDER__BUILDINGTILESET__H
#define RENDER__BUILDINGTILESET__H

#include <string>

namespace state {
  class Building;
};
namespace render {
  class TileSet;
}

#include "state/Building.h"
#include "TileSet.h"

namespace render {

  /// class BuildingTileSet - 
  class BuildingTileSet : public render::TileSet {
    // Attributes
  public:
    std::vectro<Building> buildings;
    // Operations
  public:
    BuildingTIleSet ();
    int const getBuildingWidth ();
    int const getBuildingHeight ();
    const std::string const getImageFile ();
    const Building& const getBuildingTile (char b);
    // Setters and Getters
  };

};

#endif
