// Generated by dia2code
#ifndef RENDER__BUILDINGTILESET__H
#define RENDER__BUILDINGTILESET__H

#include <string>

namespace render {
  class Tile;
};
namespace state {
  class Building;
};
namespace render {
  class TileSet;
}

#include "Tile.h"
#include "state/TypeId.h"
#include "TileSet.h"

namespace render {

  /// class BuildingTileSet - 
  class BuildingTileSet : public render::TileSet {
    // Operations
  public:
    int getTileWidth () const;
    int getTileHeight () const;
    std::string getFile () const;
    const Tile getTile (int id) const;
    const Tile getBuildingTile (const state::Building& b) const;
    state::TypeId getType () const;
    // Setters and Getters
  };

};

#endif
