// Generated by dia2code
#ifndef RENDER__RENDER__H
#define RENDER__RENDER__H

#include <SFML/Graphics.hpp>

namespace state {
  class State;
};
namespace render {
  class StatusLayer;
  class BoardLayer;
};
namespace sf {
  class RenderWindow;
};
namespace render {
  class BuildingTileSet;
  class UnitTileSet;
  class CellTileSet;
  class StateTileSet;
}

#include "StatusLayer.h"
#include "BoardLayer.h"
#include "BuildingTileSet.h"
#include "UnitTileSet.h"
#include "CellTileSet.h"
#include "StateTileSet.h"
#include "state/State.h"

namespace render {

  /// class Render - 
  class Render {
    // Associations
    // Attributes
  protected:
    /// std::shared_ptr<state::State>
    state::State& state;
    StatusLayer statusLayer;
    BoardLayer cellLayer;
    BoardLayer buildingLayer;
    BoardLayer unitLayer;
    // Operations
  public:
    Render (state::State& state);
    void draw (sf::RenderWindow& window);
    void update ();
    // Setters and Getters
    state::State& getState() const;
    void setState(const state::State&& state);
    const StatusLayer& getStatusLayer() const;
    void setStatusLayer(const StatusLayer& statusLayer);
    const BoardLayer& getCellLayer() const;
    void setCellLayer(const BoardLayer& cellLayer);
    const BoardLayer& getBuildingLayer() const;
    void setBuildingLayer(const BoardLayer& buildingLayer);
    const BoardLayer& getUnitLayer() const;
    void setUnitLayer(const BoardLayer& unitLayer);
  };

};

#endif
