// Generated by dia2code
#ifndef RENDER__SCENE__H
#define RENDER__SCENE__H

#include <stdlib.h>
#include <SFML/Graphics.hpp>

namespace state {
  class Cell;
  class Building;
  class Unit;
};
namespace render {
  class StateLayer;
};
namespace sf {
  class RenderWindow;
}

#include "StateLayer.h"
#include "state/Unit.h"
#include "state/Building.h"
#include "state/Cell.h"

namespace render {

  /// class Scene - 
  class Scene {
    // Associations
    // Attributes
  private:
    size_t  width     = 0;
    size_t  height     = 0;
    const Cell& cell;
    const Building& building;
    const Unit& unit;
    StateLayer stateLayer;
    // Operations
  public:
    Scene (const Cell& cell, const Building& building, const Unit& unit);
    size_t const getWidth ();
    size_t const getHeight ();
    void draw (sf::RenderWindow window);
    // Setters and Getters
  };

};

#endif
