// Generated by dia2code
#ifndef RENDER__STATUSLAYER__H
#define RENDER__STATUSLAYER__H


namespace render {
  class Surface;
  class TileSet;
  class Layer;
}

#include "Layer.h"

namespace render {

  /// class StatusLayer - 
  class StatusLayer : public render::Layer {
    // Operations
  public:
    StatusLayer (Surface* surface, TileSet* ts);
    StatusLayer ();
    // Setters and Getters
  };

};

#endif
