// Generated by dia2code
#ifndef RENDER__TILE__H
#define RENDER__TILE__H


namespace render {

  /// class Tile - 
  class Tile {
    // Attributes
  protected:
    int x     = 0;
    int  y     = 0;
    int  width     = 16;
    int height     = 16;
    // Operations
  public:
    Tile ();
    Tile (int x, int y, int w, int h);
    // Setters and Getters
    int getX() const;
    void setX(int x);
    const int & getY() const;
    void setY(const int & y);
    const int & getWidth() const;
    void setWidth(const int & width);
    int getHeight() const;
    void setHeight(int height);
  };

};

#endif
