// Generated by dia2code
#ifndef RENDER__TILESET__H
#define RENDER__TILESET__H

#include <string>

namespace render {
  class Tile;
};
namespace state {
  class Unit;
  class Element;
}

#include "Tile.h"
#include "state/Element.h"

namespace render {

  /// class TileSet - 
  class TileSet {
    // Operations
  public:
    virtual int getTileWidth () const = 0;
    virtual int getTileHeight () const = 0;
    virtual std::string getFile () const = 0;
    virtual const Tile getTile (int id) const = 0;
    virtual const Tile getChar (char c) const;
    virtual const Tile getUnitTile (const state::Unit& u) const;
    // Setters and Getters
  };

};

#endif
