// Generated by dia2code
#ifndef RENDER__UNITTILESET__H
#define RENDER__UNITTILESET__H

#include <string>

namespace render {
  class Tile;
};
namespace state {
  class Unit;
};
namespace render {
  class TileSet;
}

#include "Tile.h"
#include "TileSet.h"
#include "state/Unit.h"

namespace render {

  /// class UnitTileSet - 
  class UnitTileSet : public render::TileSet {
    // Operations
  public:
    int getTileWidth () const;
    int getTileHeight () const;
    std::string getFile () const;
    const Tile getTile (int id) const;
    const Tile getUnitTile (const state::Unit& u) const;
    // Setters and Getters
  };

};

#endif
