// Generated by dia2code
#ifndef AI__AI__H
#define AI__AI__H

#include <vector>

namespace state {
  class State;
};
namespace engine {
  class Command;
};
namespace state {
  class Element;
};
namespace engine {
  class Engine;
}

#include "state/State.h"
#include "engine/Command.h"
#include "engine/Engine.h"

namespace ai {

  /// class Ai - 
  class Ai {
    // Attributes
  protected:
    state::State& state;
    // Operations
  public:
    Ai (state::State& state);
    void listCommands (std::vector<engine::Command*>& list, state::Element& selected);
    virtual void run (engine::Engine& engine, state::Element& selected) = 0;
    // Setters and Getters
    state::State& getState() const;
    void setState(const state::State&& state);
  };

};

#endif
