// Generated by dia2code
#ifndef AI__AI__H
#define AI__AI__H

#include <vector>

namespace engine {
  class Command;
};
namespace state {
  class State;
  class Element;
};
namespace engine {
  class Engine;
}

#include "engine/Command.h"
#include "state/State.h"

namespace ai {

  /// class Ai - 
  class Ai {
    // Operations
  public:
    void listCommands (std::vector<engine::Command>& list, const state::State state, Element& selected);
    virtual void run (engine::Engine& engine, Element& selected) = 0;
    // Setters and Getters
  };

};

#endif
