// Generated by dia2code
#ifndef AI__AI__H
#define AI__AI__H

#include <vector>

namespace state {
  class State;
};
namespace engine {
  class Command;
};
namespace state {
  class Element;
};
namespace engine {
  class Engine;
}

#include "engine/Command.h"
#include "state/State.h"
#include "engine/Engine.h"

namespace ai {

  /// class Ai - 
  class Ai {
    // Attributes
  public:
    state::State& state;
    // Operations
  public:
    Ai ( );
    Ai (state::State& state);
    void listCommands (std::vector<engine::Command>& list, const state::State state, state::Element& selected);
    virtual void run (engine::Engine& engine, state::Element& selected) = 0;
    // Setters and Getters
  };

};

#endif
