// Generated by dia2code
#ifndef AI__CALCULDISTANCE__H
#define AI__CALCULDISTANCE__H


namespace ai {
  class Point;
}

#include "Point.h"

namespace ai {

  /// class CalculDistance - 
  class CalculDistance {
    // Attributes
  public:
    int distance;
    // Operations
  public:
    int Calculator (const Point& a, const Point& b);
    // Setters and Getters
  };

};

#endif
