// Generated by dia2code
#ifndef AI__PATHMAP__H
#define AI__PATHMAP__H

#include <vector>

namespace ai {
  class Position;
};
namespace state {
  class Element;
  class ElementTab;
}

#include "state/ElementTab.h"
#include "Position.h"

namespace ai {

  /// class PathMap - 
  class PathMap {
    // Attributes
  protected:
    int x;
    int y;
    std::vector<int> distancetab;
    // Operations
  public:
    int getDistance (const Position& a, const Position& b) const;
    const int* getDistaceTab () const;
    void init (const state::Element& element);
    void update (const state::Element& element);
    // Setters and Getters
    int getX() const;
    void setX(int x);
    int getY() const;
    void setY(int y);
    const std::vector<int>& getDistancetab() const;
    void setDistancetab(const std::vector<int>& distancetab);
  };

};

#endif
