// Generated by dia2code
#ifndef AI__POSITION__H
#define AI__POSITION__H


namespace ai {

  /// class Position - 
  class Position {
    // Attributes
  protected:
    int x;
    /// 

    int y;
    // Operations
  public:
    Position (int x = 0, int y = 0);
    // Setters and Getters
    int getX() const;
    void setX(int x);
    int getY() const;
    void setY(int y);
  };

};

#endif
