// Generated by dia2code
#ifndef ENGINE__ANTIDESTROY__H
#define ENGINE__ANTIDESTROY__H


namespace state {
  class State;
};
namespace engine {
  class AntiCommand;
}

#include "AntiCommand.h"

namespace engine {

  /// class AntiDestroy - 
  class AntiDestroy : public engine::AntiCommand {
    // Operations
  public:
    void execute (state::State& state);
    // Setters and Getters
  };

};

#endif
