// Generated by dia2code
#ifndef ENGINE__ANTIATTACK__H
#define ENGINE__ANTIATTACK__H


namespace state {
  class State;
};
namespace engine {
  class AntiCommand;
}

#include "AntiCommand.h"

namespace engine {

  /// class AntiAttack - 
  class AntiAttack : public engine::AntiCommand {
    // Operations
  public:
    void execute (state::State& state);
    // Setters and Getters
  };

};

#endif
