// Generated by dia2code
#ifndef ENGINE__ANTICOMMAND__H
#define ENGINE__ANTICOMMAND__H


namespace state {
  class State;
}

#include "CommandTypeId.h"
#include "AntiComTypeId.h"

namespace engine {

  /// class AntiCommand - 
  class AntiCommand {
    // Operations
  public:
    virtual ~AntiCommand ();
    virtual CommandTypeId getCommandTypeId () const;
    virtual AntiComTypeId getAntiCommandTypeId () const;
    virtual void execute (state::State& state) = 0;
    // Setters and Getters
  };

};

#endif
