// Generated by dia2code
#ifndef ENGINE__ANTICOMTYPEID__H
#define ENGINE__ANTICOMTYPEID__H


namespace engine {

  enum AntiComTypeId {
    ACOM_NONE,
    ACOM_ATTACK,
    ACOM_MOVE,
    ACOM_DESTROY,
    ACOM_ENDTURN
  };

};

#endif
