// Generated by dia2code
#ifndef ENGINE__ATTACKCOMMAND__H
#define ENGINE__ATTACKCOMMAND__H


namespace state {
  class Unit;
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class AttackCommand - 
  class AttackCommand : public engine::Command {
    // Attributes
  protected:
    state::Unit& attacker;
    state::Unit& defender;
    // Operations
  public:
    AttackCommand (state::Unit& attacker, state::Unit& defender);
    CommandTypeId getCommandTypeId () const;
    void execute (state::State& state);
    // Setters and Getters
    state::Unit& getAttacker() const;
    void setAttacker(const state::Unit&& attacker);
    state::Unit& getDefender() const;
    void setDefender(const state::Unit&& defender);
  };

};

#endif
