// Generated by dia2code
#ifndef ENGINE__ATTACKCOMMAND__H
#define ENGINE__ATTACKCOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "state/UnitType.h"
#include "Command.h"

namespace engine {

  /// class AttackCommand - 
  class AttackCommand : public engine::Command {
    // Attributes
  protected:
    int elementID;
    // Operations
  public:
    void attackCommand (int elementID, state::UnitType unit);
    CommandTypeId const getTypeID ();
    void excute (state::State& state);
    // Setters and Getters
    int getElementID() const;
    void setElementID(int elementID);
  };

};

#endif
