// Generated by dia2code
#ifndef ENGINE__CAPTURECOMMAND__H
#define ENGINE__CAPTURECOMMAND__H


namespace state {
  class Building;
  class Unit;
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class CaptureCommand - 
  class CaptureCommand : public engine::Command {
    // Attributes
  protected:
    state::Building& building;
    state::Unit& unit;
    // Operations
  public:
    CaptureCommand (state::Building& building, state::Unit& unit);
    CommandTypeId getCommandTypeId () const;
    void execute (state::State& state);
    // Setters and Getters
    state::Building& getBuilding() const;
    void setBuilding(const state::Building&& building);
    state::Unit& getUnit() const;
    void setUnit(const state::Unit&& unit);
  };

};

#endif
