// Generated by dia2code
#ifndef ENGINE__CAPTURECOMMAND__H
#define ENGINE__CAPTURECOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "state/CellType.h"
#include "Command.h"

namespace engine {

  /// class CaptureCommand - 
  class CaptureCommand : public engine::Command {
    // Attributes
  protected:
     charactor;
    // Operations
  public:
    void CaptureCommand (int elementID, state::CellType cell);
    commandTypeID const getTypeID ();
    void excute (state::State& state);
    // Setters and Getters
    const & getCharactor() const;
    void setCharactor(const & charactor);
  };

};

#endif
