// Generated by dia2code
#ifndef ENGINE__CHOOSEELEMENTCOMMAND__H
#define ENGINE__CHOOSEELEMENTCOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class ChooseElementCommand - 
  class ChooseElementCommand : public engine::Command {
    // Attributes
  protected:
    int elementID;
    // Operations
  public:
    void chooseElementCommand (int elementID);
    CommandTypeId getTypeId () const;
    void execute (state::State& state);
    // Setters and Getters
    int getElementID() const;
    void setElementID(int elementID);
  };

};

#endif
