// Generated by dia2code
#ifndef ENGINE__COMMANDTYPEID__H
#define ENGINE__COMMANDTYPEID__H


namespace engine {

  enum CommandTypeId {
    LOAD     = 0,
    ChooseElement     = 1,
    Attack     = 2,
    Move     = 3,
    Capture     = 4,
    Recharge     = 5,
    Repair     = 6,
    Destroy     = 7
  };

};

#endif
