// Generated by dia2code
#ifndef ENGINE__COMMAND__H
#define ENGINE__COMMAND__H


namespace state {
  class state;
};
namespace engine {
  class Engine;
}

#include "state/state.h"
#include "CommandTypeId.h"
#include "Engine.h"

namespace engine {

  /// class Command - 
  class Command {
    // Associations
    // Operations
  public:
    ~Command ();
    CommandTypeId const getTypeId ();
    void excute (state::State& state);
    // Setters and Getters
  };

};

#endif
