// Generated by dia2code
#ifndef ENGINE__COMMANDTYPEID__H
#define ENGINE__COMMANDTYPEID__H


namespace engine {

  enum CommandTypeId {
    ChooseElement     = 0,
    Attack     = 1,
    Move     = 2,
    Capture     = 3,
    Recharge     = 4,
    Repaire     = 5,
    destroy     = 6
  };

};

#endif
