// Generated by dia2code
#ifndef ENGINE__COMMAND__H
#define ENGINE__COMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Engine;
}

#include "CommandTypeId.h"
#include "state/State.h"
#include "Engine.h"

namespace engine {

  /// class Command - 
  class Command {
    // Associations
    // Attributes
  public:
    CommandTypeId commandTypeId;
    // Operations
  public:
    ~Command ();
    CommandTypeId getTypeId () const;
    void execute (state::State& state);
    // Setters and Getters
  };

};

#endif
