// Generated by dia2code
#ifndef ENGINE__COMMAND__H
#define ENGINE__COMMAND__H

#include <json/json.h>

namespace state {
  class State;
};
namespace engine {
  class AntiCommand;
};
namespace state {
  class Unit;
  class Building;
}

#include "CommandTypeId.h"
#include "AntiCommand.h"
#include "state/State.h"
#include "state/Unit.h"
#include "state/Building.h"

namespace engine {

  /// class Command - 
  class Command {
    // Operations
  public:
    virtual ~Command ();
    virtual CommandTypeId getCommandTypeId () const;
    virtual void execute (state::State& state) = 0;
    virtual void debug () const;
    virtual Json::Value toJson () const;
    // Setters and Getters
  };

};

#endif
