// Generated by dia2code
#ifndef ENGINE__DESTROYCOMMAND__H
#define ENGINE__DESTROYCOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class DestroyCommand - 
  class DestroyCommand : public engine::Command {
    // Attributes
  protected:
    state::Unit& unit;
    // Operations
  public:
    DestroyCommand (state::Unit& unit);
    CommandTypeId getCommandTypeId () const;
    void execute (state::State& state);
    // Setters and Getters
    state::Unit& getUnit() const;
    void setUnit(const state::Unit&& unit);
  };

};

#endif
