// Generated by dia2code
#ifndef ENGINE__DESTROYCOMMAND__H
#define ENGINE__DESTROYCOMMAND__H

#include <json/json.h>

namespace state {
  class Unit;
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class DestroyCommand - 
  class DestroyCommand : public engine::Command {
    // Attributes
  private:
    int unitId;
  protected:
    state::Unit& unit;
    // Operations
  public:
    DestroyCommand (state::Unit& unit);
    DestroyCommand (state::State& state, int unitId);
    CommandTypeId getCommandTypeId () const;
    void execute (state::State& state);
    void debug () const;
    Json::Value toJson () const;
    // Setters and Getters
    state::Unit& getUnit() const;
    void setUnit(const state::Unit&& unit);
  };

};

#endif
