// Generated by dia2code
#ifndef ENGINE__ENGINE__H
#define ENGINE__ENGINE__H

#include <map>
#include <memory>

namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "state/State.h"

namespace engine {

  /// class Engine - 
  class Engine {
    // Attributes
  protected:
    state::State currentState;
    std::map<int,std::shared_ptr<Command>> currentCommands;
    // Operations
  public:
    Engine ();
    ~Engine ();
    const state::State& getState () const;
    void addCommand (int priority, Command* cmd);
    void update ();
    // Setters and Getters
    const state::State& getCurrentState() const;
    void setCurrentState(const state::State& currentState);
    const std::map<int,std::shared_ptr<Command>>& getCurrentCommands() const;
    void setCurrentCommands(const std::map<int,std::shared_ptr<Command>>& currentCommands);
  };

};

#endif
