// Generated by dia2code
#ifndef ENGINE__LOADCOMMAND__H
#define ENGINE__LOADCOMMAND__H


namespace state {
  class State;
}

namespace engine {

  /// class LoadCommand - 
  class LoadCommand {
    // Attributes
  protected:
     charactor;
    // Operations
  public:
    void loadCommand (const char* charactor);
    CommandTypeId const getTypeID ();
    void excute (state::State& state);
    // Setters and Getters
    const & getCharactor() const;
    void setCharactor(const & charactor);
  };

};

#endif
