// Generated by dia2code
#ifndef ENGINE__LOADCOMMAND__H
#define ENGINE__LOADCOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class LoadCommand - 
  class LoadCommand : public engine::Command {
    // Attributes
  protected:
    state::Element selected;
    // Operations
  public:
    void loadCommand (const char* charactor);
    CommandTypeId getTypeID () const;
    void execute (state::State& state);
    // Setters and Getters
    const state::Element& getSelected() const;
    void setSelected(const state::Element& selected);
  };

};

#endif
