// Generated by dia2code
#ifndef ENGINE__RECHARGECOMMAND__H
#define ENGINE__RECHARGECOMMAND__H


#include "state/UnitType.h"

namespace engine {

  /// class RechargeCommand - 
  class RechargeCommand {
    // Attributes
  protected:
    int elementID;
    // Operations
  public:
    void RechargeCommand (int elementID, UnitType unit);
    CommandTypeId const getTypeID ();
    void excute (state::State& state);
    // Setters and Getters
    int getElementID() const;
    void setElementID(int elementID);
  };

};

#endif
