// Generated by dia2code
#ifndef ENGINE__RECHARGECOMMAND__H
#define ENGINE__RECHARGECOMMAND__H


namespace state {
  class State;
}

#include "CommandTypeId.h"
#include "state/State.h"

namespace engine {

  /// class RechargeCommand - 
  class RechargeCommand {
    // Attributes
  protected:
    int elementID;
    // Operations
  public:
    void RechargeCommand (int elementID, int targetID);
    CommandTypeId getTypeID () const;
    void execute (state::State& state);
    // Setters and Getters
    int getElementID() const;
    void setElementID(int elementID);
  };

};

#endif
