// Generated by dia2code
#ifndef ENGINE__SELECTCOMMAND__H
#define ENGINE__SELECTCOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class SelectCommand - 
  class SelectCommand : public engine::Command {
    // Attributes
  protected:
    state::Element& elem;
    // Operations
  public:
    SelectCommand (state::Element& elem);
    CommandTypeId getCommandTypeId () const;
    void execute (state::State& state);
    // Setters and Getters
    state::Element& getElem() const;
    void setElem(const state::Element&& elem);
  };

};

#endif
