// Generated by dia2code
#ifndef ENGINE__SUPPLYCOMMAND__H
#define ENGINE__SUPPLYCOMMAND__H


namespace state {
  class State;
}

#include "CommandTypeId.h"
#include "state/State.h"

namespace engine {

  /// class SupplyCommand - 
  class SupplyCommand {
    // Attributes
  protected:
    state::Unit& unit;
    // Operations
  public:
    SupplyCommand (state::Unit& unit);
    CommandTypeId getCommandTypeId () const;
    void execute (state::State& state);
    // Setters and Getters
    state::Unit& getUnit() const;
    void setUnit(const state::Unit&& unit);
  };

};

#endif
