// Generated by dia2code
#ifndef SERVER__COMMANDESERVICE__H
#define SERVER__COMMANDESERVICE__H

#include <json/json.h>

namespace engine {
  class Engine;
};
namespace server {
  class AbstractService;
  class Game;
}

#include "HttpStatus.h"
#include "AbstractService.h"
#include "engine/Engine.h"
#include "Game.h"

namespace server {

  /// class CommandeService - 
  class CommandeService : public server::AbstractService {
    // Associations
    // Attributes
  private:
    engine::Engine& engine;
    // Operations
  public:
    CommandeService (engine::Engine& engine);
    HttpStatus get (Json::Value& out, int id) const;
    HttpStatus put (Json::Value& out, const Json::Value& in) const;
    // Setters and Getters
  };

};

#endif
