// Generated by dia2code
#ifndef SERVER__COMMANDSERVICE__H
#define SERVER__COMMANDSERVICE__H

#include <json/json.h>

namespace state {
  class State;
};
namespace engine {
  class Engine;
};
namespace server {
  class AbstractService;
  class Game;
}

#include "HttpStatus.h"
#include "AbstractService.h"
#include "state/State.h"
#include "Game.h"
#include "engine/Engine.h"

namespace server {

  /// class CommandService - 
  class CommandService : public server::AbstractService {
    // Associations
    // Attributes
  private:
    state::State& state;
    engine::Engine& engine;
    // Operations
  public:
    CommandService (engine::Engine& engine);
    engine::Engine& getEngine ();
    HttpStatus get (Json::Value& out, int id) const;
    HttpStatus put (Json::Value& out, const Json::Value& in);
    // Setters and Getters
  };

};

#endif
