// Generated by dia2code
#ifndef SERVER__GAMESTATUS__H
#define SERVER__GAMESTATUS__H


namespace server {
  class Game;
}

#include "Game.h"

namespace server {

  enum GameStatus {
    CREATING     = 0,
    WAITING     = 1,
    RUNNING     = 2
  };

};

#endif
