// Generated by dia2code
#ifndef SERVER__GAME__H
#define SERVER__GAME__H

#include <vector>

namespace server {
  class Player;
}

#include "Player.h"

namespace server {

  /// class Game - 
  class Game {
    // Associations
    // Attributes
  protected:
    int places;
    std::vector<Player> players;
    // Operations
  public:
    Game ();
    Player& player (int id);
    int addPlayer (unique_ptr<Player> player);
    void removePlayer (int id);
    // Setters and Getters
    int getPlaces() const;
    void setPlaces(int places);
    const std::vector<Player>& getPlayers() const;
    void setPlayers(const std::vector<Player>& players);
  };

};

#endif
