// Generated by dia2code
#ifndef SERVER__GAME__H
#define SERVER__GAME__H


namespace server {
  class Player;
}

#include "Player.h"

namespace server {

  /// class Game - 
  class Game {
    // Associations
    // Attributes
  protected:
    int places;
    map<int,unique_ptr<Player> > players;
    // Operations
  public:
    Game ();
    Player& player (int id);
    int addPlayer (unique_ptr<Player> player);
    void removePlayer (int id);
    // Setters and Getters
    int getPlaces() const;
    void setPlaces(int places);
    const map<int,unique_ptr<Player> >& getPlayers() const;
    void setPlayers(const map<int,unique_ptr<Player> >& players);
  };

};

#endif
