// Generated by dia2code
#ifndef SERVER__GAME__H
#define SERVER__GAME__H

#include <vector>
#include <memory>

namespace server {
  class Player;
}

#include "Player.h"

namespace server {

  /// class Game - 
  class Game {
    // Associations
    // Attributes
  protected:
    std::vector<std::unique_ptr<Player>> players;
    // Operations
  public:
    Game ();
    Game (int n);
    Player& player (int id);
    const std::vector<std::unique_ptr<Player>>& getPlayers () const;
    int addPlayer (std::unique_ptr<Player> player);
    // Setters and Getters
    void setPlayers(const std::vector<std::unique_ptr<Player>>& players);
  };

};

#endif
