// Generated by dia2code
#ifndef SERVER__PLAYER__H
#define SERVER__PLAYER__H

#include <string>

namespace server {

  /// class Player - 
  class Player {
    // Attributes
  private:
    std::string name;
    bool free     = true;
    // Operations
  public:
    Player (std::string name, bool free = true);
    const std::string& getName () const;
    // Setters and Getters
  };

};

#endif
