// Generated by dia2code
#ifndef SERVER__PLAYER__H
#define SERVER__PLAYER__H


namespace server {

  /// class Player - 
  class Player {
    // Attributes
  public:
    string name;
    int age;
    bool free     = true;
    // Operations
  public:
    Player (string name, int age);
    // Setters and Getters
  };

};

#endif
