// Generated by dia2code
#ifndef SERVER__PLAYERSERVICE__H
#define SERVER__PLAYERSERVICE__H

#include <json/json.h>

namespace server {
  class PlayerDB;
  class AbstractService;
}

#include "PlayerDB.h"
#include "HttpStatus.h"
#include "AbstractService.h"

namespace server {

  /// class PlayerService - 
  class PlayerService : public server::AbstractService {
    // Associations
    // Attributes
  private:
    PlayerDB playerDB;
    // Operations
  public:
    PlayerService (PlayerDB& playerDB);
    virtual HttpStatus get (Json::Value& out, int id) const;
    virtual HttpStatus post (const Json::Value& in, int id);
    virtual HttpStatus put (Json::Value& out, const Json::Value& in);
    virtual HttpStatus remove (int id);
    // Setters and Getters
  };

};

#endif
