// Generated by dia2code
#ifndef SERVER__PLAYERDB__H
#define SERVER__PLAYERDB__H

#include <map>
#include <memory>

namespace server {
  class Player;
}

#include "Player.h"

namespace server {

  /// class PlayerDB - 
  class PlayerDB {
    // Associations
    // Attributes
  public:
    std::map<int,std::unique_ptr<Player>> players;
    int idseq;
    // Operations
  public:
    PlayerDB ();
    const Player* getPlayer (int id) const;
    int addPlayer (std::unique_ptr<Player> player);
    void setPlayer (int id, std::unique_ptr<Player> player);
    void removePlayer (int id);
    // Setters and Getters
  };

};

#endif
