// Generated by dia2code
#ifndef SERVER__SERVICEEXCEPTION__H
#define SERVER__SERVICEEXCEPTION__H

#include <string>

namespace server {

  /// class ServiceException - 
  class ServiceException {
    // Attributes
  protected:
    std::string msg;
    // Operations
  public:
    ServiceException ();
    // Setters and Getters
    const std::string& getMsg() const;
    void setMsg(const std::string& msg);
  };

};

#endif
