#ifndef COMMANDGENERATION_H
#define COMMANDGENERATION_H

#include <iostream>
#include <fstream>
#include "state.h"
#include "engine.h"

using namespace std ;
using namespace state ;
using namespace engine ;

/*====== WORKS WITH CONSTANT TEST MAP GENERATED BY generateTest*(*) IN MapGeneration ======*/

namespace CommandGeneration{
    void generateCommand(Engine& engine);
    std::vector<Command*> generateCommandList(Engine& engine);
};

#endif 