// Generated by dia2code
#ifndef __ENGINE__H
#define __ENGINE__H

#include "engine/Engine.h"
#include "engine/CommandTypeId.h"
#include "engine/Command.h"
#include "engine/AttackCommand.h"
#include "engine/SelectCommand.h"
#include "engine/MoveCommand.h"
#include "engine/CaptureCommand.h"
#include "engine/SupplyCommand.h"
#include "engine/RepairCommand.h"
#include "engine/DestroyCommand.h"
#include "engine/LoadCommand.h"
#endif
