// Generated by dia2code
#ifndef __ENGINE__H
#define __ENGINE__H

#include "engine/Engine.h"
#include "engine/CommandTypeId.h"
#include "engine/Command.h"
#include "engine/AttackCommand.h"
#include "engine/ChooseElementCommand.h"
#include "engine/MoveCommand.h"
#include "engine/CaptureCommand.h"
#include "engine/RechargeCommand.h"
#include "engine/RepaireCommand.h"
#include "engine/DestroyCommand.h"
<<<<<<< HEAD
=======
#include "engine/LoadCommand.h"
>>>>>>> f4bd69d13f3c442d4db8e7f66ef607a0b7fb144e
#endif
