// Generated by dia2code
#ifndef __RENDER__H
#define __RENDER__H

#include "render/Surface.h"
#include "render/Tile.h"
#include "render/TileSet.h"
#include "render/Layer.h"
#include "render/StateLayer.h"
#include "render/CellTileSet.h"
#include "render/Scene.h"
#include "render/InterfaceLayer.h"
#include "render/UnitTileSet.h"
#include "render/BuildingTileSet.h"
#endif
