// Generated by dia2code
#ifndef STATE__BUILDING__H
#define STATE__BUILDING__H


#include "BuildingType.h"
#include "BuildingTeam.h"

namespace state {

  /// class Building - 
  class Building {
    // Associations
    // Attributes
  protected:
    int x;
    int y;
    int capturePoints ;
    BuildingType buildingType;
    BuildingTeam buildingTeam;
    // Operations
  public:

    // Setters and Getters
    BuildingType getBuildingType ();
    BuildingTeam getTeam ();
    int getX() const;
    void setX(int X);
    int getY() const;
    void setY(int Y);
    int getCapturePoints() const;
    void setCapturePoints(int capturePoints);
    bool isInCapture ();
  };

};

#endif
