// Generated by dia2code
#ifndef STATE__CELL__H
#define STATE__CELL__H
#include <memory>

namespace state {
  class Building;
  class Unit;
}

#include "CellType.h"
#include "Building.h"
#include "Unit.h"

namespace state {

  /// class Cell - 
  class Cell {
    // Associations
    // Attributes
  protected:
    int x;
    int y;
    CellType celltype;
    unique_ptr<Building> building;
    Unit* unit;
    // Operations
  public:
    Building* getBuilding ();
    Unit* getUnit ();
    CellType getCellType ();
    // Setters and Getters
    int getX() const;
    void setX(int X);
    int getY() const;
    void setY(int Y);
  };

};

#endif
