// Generated by dia2code
#ifndef STATE__CELLTYPE__H
#define STATE__CELLTYPE__H


namespace state {

  enum CellType {
    GROUND     = 0,
    ROAD     = 1,
    FOREST     = 2,
    MOUNTAIN     = 3,
    RIVER     = 4,
    BRIDGE     = 5,
    SEA     = 6,
    BUILDING     = 7,
    BASE     = 8
  };

};

#endif
