// Generated by dia2code
#ifndef STATE__UNIT__H
#define STATE__UNIT__H


#include "UnitType.h"
#include "UnitTeam.h"

namespace state {

  /// class Unit - 
  class Unit {
    // Associations
    // Attributes
  protected:
    int x;
    int y;
    int health     = 100;
    int ammo;
    int fuel;
    int vision;
    UnitType unittype;
    UnitTeam unitteam;
    // Operations
  public:
    UnitType getUnitType ();
    UnitTeam getTeam ();
    bool isInfantry ();
    //bool isCapturing ();
    bool isRanged ();
    bool isTransporter ();
    // Setters and Getters
    int getX() const;
    void setX(int X);
    int getY() const;
    void setY(int Y);
    int getHealth() const;
    void setHealth(int Health);
    int getAmmo() const;
    void setAmmo(int Ammo);
    int getFuel() const;
    void setFuel(int Fuel);
    int getVision() const;
    void setVision(int Vision);
  };

};

#endif
