// Generated by dia2code
#ifndef CLIENT__CLIENT__H
#define CLIENT__CLIENT__H


namespace engine {
  class Engine;
}

#include "engine/Engine.h"

namespace client {

  /// class Client - 
  class Client {
    // Associations
    // Attributes
  private:
    engine::Engine engine;
    // Operations
  public:
    Client ();
    void run ();
    // Setters and Getters
  };

};

#endif
