// Generated by dia2code
#ifndef CLIENT__CLIENT__H
#define CLIENT__CLIENT__H


namespace client {

  /// class Client - 
  class Client {
    // Attributes
  private:
    engine::Engine engine;
    // Operations
  public:
    Client ();
    run ();
    // Setters and Getters
  };

};

#endif
