// Generated by dia2code
#ifndef UNITDESCRIPTION__H
#define UNITDESCRIPTION__H

/// class UnitDescription - A placer dans le package de règles
class UnitDescription {
  // Attributes
protected:
  string UnitName;
  WeaponType weapon1Type;
  int weapon1Power;
  int weapon1MaxAmmo;
  string weapon1Name;
  WeaponType weapon2Type;
  int weapon2Power;
  string weapon2Name;
  ArmorType armorType;
  int armorPower;
  int maxFuel   = 99;
  MovementType movBehaviour;
  int movementRange;
  int rangeMin;
  int rangeMax;
  // Setters and Getters
  const string& getUnitName() const;
  void setUnitName(const string& UnitName);
  const WeaponType& getWeapon1Type() const;
  void setWeapon1Type(const WeaponType& weapon1Type);
  int getWeapon1Power() const;
  void setWeapon1Power(int weapon1Power);
  int getWeapon1MaxAmmo() const;
  void setWeapon1MaxAmmo(int weapon1MaxAmmo);
  const string& getWeapon1Name() const;
  void setWeapon1Name(const string& weapon1Name);
  const WeaponType& getWeapon2Type() const;
  void setWeapon2Type(const WeaponType& weapon2Type);
  int getWeapon2Power() const;
  void setWeapon2Power(int weapon2Power);
  const string& getWeapon2Name() const;
  void setWeapon2Name(const string& weapon2Name);
  const ArmorType& getArmorType() const;
  void setArmorType(const ArmorType& armorType);
  int getArmorPower() const;
  void setArmorPower(int armorPower);
  int getMaxFuel() const;
  void setMaxFuel(int maxFuel);
  const MovementType& getMovBehaviour() const;
  void setMovBehaviour(const MovementType& movBehaviour);
  int getMovementRange() const;
  void setMovementRange(int movementRange);
  int getRangeMin() const;
  void setRangeMin(int rangeMin);
  int getRangeMax() const;
  void setRangeMax(int rangeMax);
};

#endif
