// Generated by dia2code
#ifndef __RENDER__H
#define __RENDER__H

#include "render/Tile.h"
#include "render/TileSet.h"
#include "render/Surface.h"
#include "render/Layer.h"
#include "render/StatusLayer.h"
#include "render/BoardLayer.h"
#include "render/BuildingTileSet.h"
#include "render/UnitTileSet.h"
#include "render/CellTileSet.h"
#include "render/StateTileSet.h"
#include "render/Render.h"
#endif
